### ISSUE TITLE
Please add a license to your repo

### ISSUE THREAD

**Issue by YoSiJo** [perryflynn/acme.sh-inwx#2]
I can't get any information from your repo under which license you put it. Please add a license information.

**Comment by perryflynn** [comment]
Hi,

inwx is now part the official acme.sh code [1].

I will remove this repository in the near time because it is not needed anymore. 

(I don't use it anymore, too)

[1]: https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_inwx.sh
